const mongoose = require('mongoose');

const MONGO_URI = 'mongodb+srv://SrkiTomic93:Dekadeka93@cluster0.zeyuaxo.mongodb.net/?appName=Cluster0';

const questionSchema = new mongoose.Schema({
    q: String,
    answers: [String],
    correct: Number,
    category: { type: String, default: 'opsta_kultura' }
});

const Question = mongoose.model('Question', questionSchema);

const questions = [
    {q: "Ko je napisao 'Proces'?", answers: ["Franc Kafka", "Herman Hese", "Tomas Man", "Robert Muzil"], correct: 0 },
    {q: "Šta je Pitagorina teorema?", answers: ["a² + b² = c²", "E = mc²", "F = ma", "V = IR"], correct: 0 },
    {q: "Koji je glavni grad Toga?", answers:  ["Abidžan", "Lome", "Najrobi", "Kinsaša"], correct: 1 },
    {q: "Osnivac stoicizma je ?", answers: ["Zenon", "Platon", "Niče", "Arhimed"], correct: 0 },
    { q: "Koji element je najzastupljeniji u Zemljinoj atmosferi?", answers: ["Kiseonik", "Ugljen-dioksid", "Azot", "Vodonik"], correct: 2 },
    {q: "Roman Dorucak kod Tifanija je pisao", answers: ["Bred Iston", "Truman Kapote", "Tes Geritsen", "Tomas Haris"], correct: 1 },
    {q: "Kolliko godina je trajao stogodisnji rat?", answers: ["116", "118", "87", "105"], correct: 0},
    {q: "Povrsinski gledano najmanja drzava Azije je ?", answers: ["Sri Lanka", "Singapur", "Brunej", "Maldivi"], correct: 3},
    { q: "Koji je najveći sisar na planeti?", answers: ["Afrički slon", "Plavi kit", "Žirafa", "Kit ajkula"], correct: 1 },
    { q: "Koliko ima nula u broju milion?", answers: ["3", "4", "5", "6"], correct: 3 },
    {q: "Medju rimski car od ponudjenih ne spada u tkz.dobre", answers: ["Nerva", "Trajan", "Hadrijan", "Konstantin"], correct: 3},
    {q: "Koji je glavni grad Nikaragve?", answers: ["Managva", "Asonsion", "Port taun", "Tegucigalpa"], correct: 0 },
    {q: "Koje godine je rodjen pisac Danilo Kiš?", answers: ["1925", "1935", "1945", "1955"], correct: 1 },
    {q: "Ko je napisao 'Stranca'?", answers: ["Žan-Pol Sartr", "Alber Kami", "Simon de Bovoar", "Marsel Prust"], correct: 1 },
    {q: "Merna jedinica za magnetni fluks je?", answers: ["Veber", "Henri", "Tesla", "Kulon"], correct: 0 },
    {q: "Ko je autor 'Države'?", answers: ["Aristotel", "Sokrat", "Platon", "Seneka"], correct: 2 },
    { q: "Ko je prvi predložio teoriju evolucije prirodnom selekcijom (zajedno sa Darvinom)?", answers: ["Žan-Batist Lamark", "Alfred Rasel Volas", "Tomas Maltus", "Čarls Lajel"], correct: 1 },
    {q: "Koliko iznosi molarna masa vode (H₂O)?", answers: ["16 g/mol", "18 g/mol", "20 g/mol", "22 g/mol"], correct: 1 },
    {q: "Ko je bio kralj Franaka i prvi car Svetog rimskog carstva?", answers: ["Klodvig", "Karlo Martel", "Karlo Veliki", "Fridrih Barbarosa"], correct: 2 },
    {q: "Koja je najmanja kost u ljudskom telu?", answers: ["Čekić", "Nakovanj", "Uzengija", "Puž"], correct: 2 },
    {q: "Koji je glavni grad Tanzanije?", answers: ["Najrobi", "Dodoma", "Kampala", "Kigali"], correct: 1 },
    {q: "Ko je otkrio strukturu DNK?", answers: ["Darvin i Volas", "Mendel i Morgan", "Votson i Krik", "Paster i Koh"], correct: 2 },
    {q: "Koje godine je počela Francuska revolucija?", answers: ["1776", "1789", "1799", "1804"], correct: 1 },
    {q: "Šta je 'kogito ergo sum' na srpskom?", answers: ["Znam da ništa ne znam", "Mislim, dakle postojim", "Sve je broj", "Biti ili ne biti"], correct: 1 },
    {q: "Koji je drugi najveći kontinent na svetu?", answers: ["Severna Amerika", "Južna Amerika", "Afrika", "Azija"], correct: 2 },
    {q: "Koji je glavni grad Kanade?", answers: ["Toronto", "Vankuver", "Montreal", "Otava"], correct: 3 },
    {q: "Nama najbliza zvezda posle sunca je ?", answers: ["Proksima Kentauri", "Berndova zvezda ", "Vajs", "B-192"], correct: 0 },
    {q: "Tim koji je osvojio fudbalsko prvenstovo Jugoslavije za sezonu 1970/1971?", answers: ["Partizan", "Dinamo Zagreb", "Hajduk Split", "Vojvodina"], correct: 2},
    {q: "Koji je najbrži sisar na svetu?", answers: ["Lav", "Antilopa", "Gepard", "Konj"], correct: 2 },
    {q: "Koji je najviši planinski vrh Afrike?", answers: ["Atlas", "Drakensberg", "Kilimandžaro", "Kenija"], correct: 2 },
    {q: "Šta je predstavlja Hablova konstanta?", answers: ["Masu crne rupe", "Starost univerzuma", "Brzinu širenja svemira", "Gustinu tamne materije"], correct: 2 },
    {q: "Koliko traje mandat američkog senatora?", answers: ["2 godine", "4 godine", "6 godina", "8 godina"], correct: 2 },
    {q: "Šta je glavna funkcija mitohondrija u ćeliji?", answers: ["Sinteza proteina", "Skladištenje masti", "Proizvodnja ATP-a", "Razgradnja otrova"], correct: 2 },
    {q: "Koji naučnik je predložio heliocentrični model Sunčevog sistema?", answers: ["Ptolomej", "Kopernik", "Galilej", "Kepler"], correct: 1 },
    {q: "Ko je autor knjige 'Kratka istorija vremena'?", answers: ["Ričard Fajnman", "Karl Segan", "Stiven Hoking", "Nil Degras Tajson"], correct: 2 },
    {q: "Koji je glavni grad Ekvadora?", answers: ["Bogota", "Karakas", "Limu", "Kito"], correct: 3 },
    {q: "Koliko ima kraljeva u standardnom špilu karata?", answers: ["2", "3", "4", "6"], correct: 2 },
    {q: "Koliko ima bajtova u jednom megabajtu (tehnički tačno)?", answers: ["1000", "1024", "1048576", "1000000"], correct: 2 },
    {q: "Ko je naslikao 'Rođenje Venere'?", answers: ["Leonardo", "Mikelandjelo", "Botičeli", "Rafael"], correct: 2 },
    {q: "Koji je glavni grad Slovenije?", answers: ["Zagreb", "Sarajevo", "Ljubljana", "Podgorica"], correct: 2 },
    {q: "Koliko amandmana ima Ustav SAD (uključujući prvih deset Povelje o pravima)?", answers: ["10", "17", "27", "33"], correct: 2 },
    { q: "Ko je komponovao 'Mesečevu sonatu'?", answers: ["Mocart", "Bach", "Betoven", "Brams"], correct: 2 },
    {q: "Ko je napisao 'Zov divljine'?", answers: ["Ernest Hemingvej", "Džek London", "Mark Tven", "Herman Melvil"], correct: 1 },
    {q: "Koji je najgušći element u prirodi?", answers: ["Olovo", "Zlato", "Platina", "Osmijum"], correct: 3 },
    {q: "U kojoj zemlji se nalazi regija Flandrija?", answers: ["Holandija", "Luksemburg", "Belgija", "Nemačka"], correct: 2 },
    {q: "Tvorac Talicnog Toma je ?", answers: ["Moris", "Kobe", "Fransao", "Eduard"], correct: 0 },
    {q: "Smrt u Veneciji je napisao?", answers: ["Herman Hese", "Vladimir Pistalo", "Tomas Man", "Agata Kristi"], correct: 2 },
    {q: "U kom veku je živela Jovanka Orleanka?", answers: ["13. vek", "14. vek", "15. vek", "16. vek"], correct: 2 },
    {q: "Koji je glavni grad Čilea?", answers: ["Santjago", "La Paz", "Lima", "Bogota"], correct: 0 },
    { q: "Koje godine je izbila Kratka skupština u Engleskoj?", answers: ["1628", "1640", "1642", "1653"], correct: 1 },
    { q: "Koji je glavni grad Surinama?", answers: ["Paramaribo", "Džordžtaun", "Kajena", "Bridžtaun"], correct: 0 },
    { q: "Ko je autor 'Fenomenologije duha'?", answers: ["Kant", "Fihte", "Hegel", "Šeling"], correct: 2 },
    { q: "Koliko simfonija je komponovao Žan Sibelijus?", answers: ["5", "7", "9", "12"], correct: 1 },
    { q: "Koji je hemijski simbol za volfram?", answers: ["V", "W", "T", "Tu"], correct: 1 },
    { q: "Na kojoj reci leži grad Firenca?", answers: ["Tibar", "Po", "Arno", "Adige"], correct: 2 },
    { q: "Koje godine je potpisan Vestfalski mir?", answers: ["1618", "1635", "1648", "1659"], correct: 2 },
    { q: "Ko je napisao 'Logičko-filozofski traktat'?", answers: ["Bertrand Rasel", "Rudolf Karnap", "Ludvig Vitgenštajn", "Gotlob Frege"], correct: 2 },
    { q: "Šta je Džejms Klerk Maksvel ujedinio svojim jednačinama?", answers: ["Gravitaciju i svetlost", "Elektricitet i magnetizam", "Prostor i vreme", "Masu i energiju"], correct: 1 },
    { q: "U kojoj zemlji se nalazi regija Patagonija?", answers: ["Brazil i Urugvaj", "Čile i Argentina", "Peru i Bolivija", "Kolumbija i Ekvador"], correct: 1 },
    { q: "Ko je bio poslednji vizantijski car?", answers: ["Justinijan I", "Konstantin XI Paleolog", "Vasilije II Bugaroubica", "Aleksije I Komnin"], correct: 1 }, 
    { q: "Koliko iznosi Plankova konstanta (red veličine u J·s)?", answers: ["10⁻²⁰", "10⁻²⁴", "10⁻³⁴", "10⁻⁴⁰"], correct: 2 },
    { q: "Ko je autor romana 'Doktor Faustus'?", answers: ["Herman Hese", "Tomas Man", "Franc Kafka", "Robert Muzil"], correct: 1 },
    { q: "Koji faraon je izgradio Abu Simbel?", answers: ["Ramzes II", "Tutankamon", "Ehnaton", "Hatshepsut"], correct: 0 },
    { q: "Koji je glavni grad Butana?", answers: ["Katmandu", "Timpu", "Naypyidaw", "Daka"], correct: 1 },
    { q: "Šta je 'Dama sa hermelinom'?", answers: ["Skulptura Mikelanđela", "Slika Leonarda da Vinčija", "Mozartova opera", "Rembrantova slika"], correct: 1 },
    { q: "Ko je otkrio princip Arhimedovog zavrtnja?", answers: ["Arhimed", "Pitagora", "Euklid", "Aristotel"], correct: 0 },
    { q: "Koje godine je osnovano Kraljevstvo Srba, Hrvata i Slovenaca?", answers: ["1914", "1918", "1919", "1921"], correct: 1 },
    { q: "Koji je najmanji element u periodnom sistemu?", answers: ["Vodonik", "Helijum", "Litijum", "Berilijum"], correct: 0 },
    { q: "U kojoj galaksiji se nalazi naš Sunčev sistem?", answers: ["Andromeda", "Mlečni put", "Magelanov oblak", "Sombrero"], correct: 1 },
    { q: "Ko je bio lider pokreta 'Nesvrstani' uz Tita?", answers: ["Indira Gandi", "Gamal Abdel Naser", "Džavaharlal Nehru", "Hajle Selasije"], correct: 2 },
    { q: "Šta je 'ogdoade' u egipatskoj mitologiji?", answers: ["Knjiga mrtvih", "Grupa od osam prvobitnih bogova", "Faraonova grobnica", "Sveti skarabej"], correct: 1 },
    { q: "Ko je naslikao 'Vrisak'?", answers: ["Gustav Klimt", "Edvard Munk", "Egon Šile", "Vasilij Kandinski"], correct: 1 },
    { q: "Koliko atoma ima u molekulu glukoze (C₆H₁₂O₆)?", answers: ["12", "18", "24", "36"], correct: 2 },
    { q: "Koji je najviši planinski vrh u Evropi (po većini definicija granice kontinenata)?", answers: ["Mon Blan", "Elbrus", "Dufour", "Materhorn"], correct: 1 },
    { q: "Ko je autor 'Tragedije čoveka'?", answers: ["Šandor Petefi", "Imre Madač", "Endre Adi", "Atila Jožef"], correct: 1 },
    { q: "Koje godine je izbila Bokserska pobuna u Kini?", answers: ["1898", "1900", "1905", "1911"], correct: 1 },
    { q: "Šta je Sokratov metod?", answers: ["Posmatranje prirode", "Dijalektička rasprava pitanjima", "Matematičko dokazivanje", "Meditacija"], correct: 1 },
    { q: "Koji je najgušći gas?", answers: ["Radon", "Ksenon", "Kripton", "Argon"], correct: 0 },
    { q: "Ko je osvojio Zlatnu palmu 2023. godine?", answers: ["Džim Džarmuš", "Nuri Bilge Džejlan", "Žistin Trije", "Aki Kaurismaki"], correct: 2 },
    { q: "Koliko traje period poluraspada ugljenika-14?", answers: ["oko 1.500 godina", "oko 5.730 godina", "oko 12.000 godina", "oko 50.000 godina"], correct: 1 },
    { q: "Ko je napisao 'Šagrenovu kožu'?", answers: ["Viktor Igo", "Onore de Balzak", "Stendal", "Gistav Flober"], correct: 1 },
    { q: "U kojoj bici je poginuo kralj Harold II 1066. godine?", answers: ["Bici kod Azinkura", "Bici kod Krešija", "Bici kod Hejstingsa", "Bici kod Poatjea"], correct: 2 },
    { q: "Koji je glavni grad Kirgistana?", answers: ["Almati", "Taškent", "Dušanbe", "Biškek"], correct: 3 },
    { q: "Šta su 'Bozoni' u fizici?", answers: ["Čestice materije", "Prenosioci sila", "Antičestice", "Tamna materija"], correct: 1 },
    { q: "Ko je režirao 'Sati'?", answers: ["Virdžinija Vulf", "Stiven Daldri", "Dejvid Linč", "Piter Džekson"], correct: 1 },
    { q: "Koliko stepeni ima u pravom uglu?", answers: ["45", "60", "90", "120"], correct: 2 },
    { q: "Ko je autor 'Hvalisavog ratnika' (Miles Gloriosus)?", answers: ["Terentius", "Plaut", "Seneka", "Plutarh"], correct: 1 },
    { q: "Koji je najduži autoput u Srbiji (trenutno)?", answers: ["A1", "A2", "A3", "A4"], correct: 0 },
    { q: "Šta je 'entropija'?", answers: ["Mera količine energije", "Mera nereda u sistemu", "Mera brzine svetlosti", "Mera gravitacije"], correct: 1 },
    { q: "Ko je napisao 'Besnilo'?", answers: ["Borislav Pekić", "Danilo Kiš", "Milorad Pavić", "Aleksandar Tišma"], correct: 0 },
    { q: "Koji je glavni grad Belizea?", answers: ["Belmopan", "Gvatemala", "San Salvador", "Tegusigalpa"], correct: 0 },
    { q: "Koliko traje jedan siderički mesec?", answers: ["oko 27,3 dana", "oko 28,5 dana", "oko 29,5 dana", "oko 30 dana"], correct: 0 },
    { q: "Ko je komponovao 'Sliku sa izložbe'?", answers: ["Petar Iljič Čajkovski", "Modest Musorgski", "Sergej Rahmanjinov", "Mihail Glinka"], correct: 1 },
    { q: "U kojoj državi se nalazi Silicijumska dolina?", answers: ["Teksas", "Njujork", "Kalifornija", "Vašington"], correct: 2 },
    { q: "Koji je hemijski simbol za zlato?", answers: ["Zl", "Go", "Au", "Ag"], correct: 2 },
    {q: "Od cijeg mleka se pravi kumis?", answers: ["kravljeg", "kamiljeg", "kozijeg", "kobiljeg"], correct: 3 },
    { q: "Koji je glavni grad Kambodže?", answers: ["Hanoj", "Vijentijan", "Pnom Pen", "Bangkok"], correct: 2 }, 
    { q: "Koliko elektrona ima atom ugljenika u neutralnom stanju?", answers: ["4", "6", "8", "12"], correct: 1 },
    { q: "Ko je bio prvi predsednik Južne Afrike posle aparthejda?", answers: ["Stiv Biko", "Nelson Mandela", "F. V. de Klerk", "Tabo Mbeki"], correct: 1 },
    { q: "Koje godine je potpisano primirje u Prvom svetskom ratu?", answers: ["1916", "1917", "1918", "1919"], correct: 2 },
    { q: "Koji je najdublji okeanski rov na svetu?", answers: ["Portorikanski", "Javanski", "Marijanski", "Tonga"], correct: 2 },
    { q: "Koji filozof je autor 'Kritike čistog uma'?", answers: ["Hjum", "Lok", "Kant", "Berkli"], correct: 2 },
    { q: "Šta je glavna jedinica nasleđivanja?", answers: ["Hromozom", "Protein", "Gen", "Ribozom"], correct: 2 },
    {q: "Kosinus ugla od 90 stepeni iznosi?", answers: ["0", "1", "beskonacno", "1/2"], correct: 0 },
    {q: "Kakve pesme je najvise pevala Vasilija Radojcic?", answers: ["narodne", "pop", "džez", "bluz"], correct: 0 },
    {q: "Koja od sestara Bronte je napisala roman Džejn Ejr?", answers: ["Šarlota", "Emili", "Ana", "nijedna"], correct: 0 },
    {q: "Kojoj porodici biljaka pripada kleka, glavni sastojak klekovače?", answers: ["bukava", "borova", "čempresa", "ruža"], correct: 2 },
    {q: "Roman Stepski vuk je napisao?", answers: ["Tomas Man", "Ljorka", "Ivo Andrić", "Herman Hese"], correct: 3 },
    {q: "Ko je bio prvi predsednik Praviteljstvujuščeg sovjeta serbskog?", answers: ["prota M.Nenadović", "Jakov Nenadović", "Karađorđe Petrović", "Branko Radičević"], correct: 0 },
    {q: "Po kom piću je popularno nazvana revolucija u Vojvodini 1988.godine?", answers: ["vinjaku", "bozi", "jogurtu", "čaju"], correct: 2 },
    { q: "Koja je najmanja država na svetu?", answers: ["Monako", "Vatikan", "San Marino", "Lihtenštajn"], correct: 1 },
    {q: "Koja reka se pominje u pesmi Sanja, grupe Alisa?", answers: ["Dunav", "Sava", "Morava", "Amazon"], correct: 0 },
    {q: "Za koji roman je Ernest Hemingvej 1953.godine dobio Pulicerovu nagradu?", answers: ["Za kim zvono zvoni", "Zbogom oružje", "Starac i more", "Snegovi Kilimandžara"], correct: 2 },
    {q: "Koji grad je domaćin manifestacije Mokranjčevi dani?", answers: ["Sombor", "Negotin", "Zaječar", "Požarevac"], correct: 1 },
    {q: "U kom veku je Henri Osmi vladao Engleskom?", answers: ["14.vek", "15.vek", "16.vek", "17.vek"], correct: 2 },
    {q: "U kojoj ulici živi Banamen?", answers: ["Akacija", "Bejker", "Visterija Lejn", "nema ulicu"], correct: 0 },
    {q: "Koja obala Australije izlazi na Veliki australijski zaliv?", answers: ["južna", "istočna", "zapadna", "severna"], correct: 0 },
    { q: "Džeki Iks je proslavljeni?", answers: ["glumac", "automobilista", "ulični umetnik", "stilista"], correct: 1 },
    { q: "U kojom od navedenih filmova ne glumi Hemfri Bogart?", answers: ["Kazablanka", "Blago Sijera Madre", "Afrička kraljica", "Pozovi M radi ubistva"], correct: 3 },
    { q: "U kom filmu ne glumi Odri Hebert?", answers: ["Sabrina", "Doručak kod Tifanija", "Praznik u Rimu", "Desilo se jedne noći"], correct: 3 },
    { q: "Koje ime dele glumici Selek,Skerit i Berindžer?", answers: ["Tom", "Sem", "Džim", "Džon"], correct: 0 },
    { q: "Koja Verdijeva opera je zasnovana na romanu Dama s kamelijama?", answers: ["Trubadur", "Travijata", "Rigoleto", "Nabuko"], correct: 1 },
    { q: "Mrtve duše je napisao?", answers: ["Tolstoj", "Dostojevski", "Bulgarski", "Gogolj"], correct: 3 },
    { q: "Vajfertovu pivaru vezujemo za koji grad?", answers: ["Pančevo", "Apatin", "Negotin", "Čelarevo"], correct: 0 },
    { q: "Prvu biografiju Vuka Karađžića napisao je?", answers: ["Ljubomir Stojanović", "Izmail Sreznjevski", "Miodrag Popović", "Branko Radičević"], correct: 1 },
    { q: "Vakslerova skala se koristi za merenje ?", answers: ["stepena zagađenosti vazduha", "stope razvoda brakova", "vazdušnog pritiska", "koeficijenta inteligencije"], correct: 3 },
    { q: "15 procenata od 350?", answers: ["48.5", "52.5", "57.5", "62"], correct: 1 },
    { q: "Tajnu večeru je naslikao ?", answers: ["Da Vinči", "Mikelanđelo", "Karavađo", "Rafaelo"], correct: 0 },
    { q: "pesmu Kad spavaš sam izvodi?", answers: ["Bajaga", "Yu grupa", "Kerber", "Smak"], correct: 3 },
    { q: "Ko je autor 'Uspona i pada Rimskog carstva'?", answers: ["Edvard Gibon", "Arnold Tojnbi", "Herodot", "Plutarh"], correct: 0 },
    { q: "Ko je naslikao 'Guernicu'?", answers: ["Salvador Dali", "Hoan Miro", "Pablo Pikaso", "Francisko Goja"], correct: 2 },
    { q: "Koliko iznosi brzina svetlosti u vakuumu (približno)?", answers: ["300.000 km/h", "300.000 km/s", "3.000.000 km/s", "30.000 km/s"], correct: 1 },
    { q: "Koji je glavni grad Letonije?", answers: ["Viljnus", "Talin", "Riga", "Helsinki"], correct: 2 },
    { q: "Ako bi bilo koji pozitivan broj stepenovali sa nulom dobili bi?", answers: ["0", "1", "vrednost tog broja", "beskonačno"], correct: 1},
    { q: "Koji je najveći okean na svetu?", answers: ["Atlantski", "Indijski", "Tihi", "Južni"], correct: 2 },
    { q: "Ko je napisao 'Zločin i kazna'?", answers: ["Lav Tolstoj", "Fjodor Dostojevski", "Nikolaj Gogolj", "Ivan Turgenjev"], correct: 1 },
    { q: "Koji hemijski element ima simbol 'O'?", answers: ["Osmijum", "Kiseonik", "Olovo", "Oganeson"], correct: 1 },
    { q: "Koliko ima minuta u jednom danu?", answers: ["1440", "1240", "1640", "1340"], correct: 0 },
    { q: "Koja je najveća pustinja na svetu?", answers: ["Sahara", "Gobi", "Antarktička", "Kalahari"], correct: 2 },
    { q: "Ko je naslikao 'Zvezdanu noć'?", answers: ["Pikaso", "Rembrant", "Van Gog", "Mone"], correct: 2 },
    { q: "Koji je najduži rečni sistem na svetu?", answers: ["Nil", "Amazon", "Jangce", "Misisipi"], correct: 0 },
    { q: "U kojoj godini je pao Berlinski zid?", answers: ["1987", "1988", "1989", "1990"], correct: 2 },
    { q: "Koji vitamin se dobija od sunčeve svetlosti?", answers: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin B12"], correct: 2 },
    { q: "Koji je najmanji kontinent?", answers: ["Evropa", "Južna Amerika", "Antarktik", "Australija"], correct: 3 },
    { q: "Ko je bio prvi predsednik SAD?", answers: ["Tomas Džeferson", "Abraham Linkoln", "Džordž Vašington", "Bendžamin Frenklin"], correct: 2 },
    { q: "Koliko ima sekundi u jednom satu?", answers: ["360", "3600", "60", "600"], correct: 1 },
    { q: "Koji je najviši vodopad na svetu?", answers: ["Viktorijini", "Nijagarini", "Anđeoski", "Iguasu"], correct: 2 },
    { q: "Koji grčki bog je bio vladar podzemlja?", answers: ["Zevs", "Posejdon", "Had", "Ares"], correct: 2 },
    { q: "Koji je hemijski simbol za srebro?", answers: ["S", "Sr", "Si", "Ag"], correct: 3 },
    { q: "U kojoj zemlji se nalazi Maču Pikču?", answers: ["Kolumbija", "Peru", "Brazil", "Argentina"], correct: 1 },
    { q: "Ko je otkrio penicilin?", answers: ["Luj Paster", "Robert Koh", "Aleksandar Fleming", "Hauard Floraj"], correct: 2 },
    { q: "Koliko ima dana u redovnoj godini?", answers: ["364", "365", "366", "360"], correct: 1 },
    { q: "Kako se zove najveća kost u ljudskom telu?", answers: ["Lobanja", "Karlica", "Butna kost", "Rebro"], correct: 2 },
    { q: "Koji je glavni grad Grčke?", answers: ["Solun", "Larisa", "Atina", "Patra"], correct: 2 },
    { q: "Ko je napisao 'Gordost i predrasude'?", answers: ["Šarlota Bronte", "Emili Bronte", "Džejn Ostin", "Virdžinija Vulf"], correct: 2 },
    { q: "Koliko iznosi broj π (pi) zaokružen na dve decimale?", answers: ["3.12", "3.14", "3.16", "3.18"], correct: 1 },
    { q: "Koja zemlja je poznata kao 'Zemlja hiljadu jezera'?", answers: ["Švedska", "Norveška", "Finska", "Kanada"], correct: 2 },
    { q: "Ko je bio otac psihoanalize?", answers: ["Karl Jung", "Alfred Adler", "Ivan Pavlov", "Sigmund Frojd"], correct: 3 },
    { q: "Koji je glavni grad Australije?", answers: ["Sidnej", "Melburn", "Kambera", "Pert"], correct: 2 },
    { q: "Ko je napisao 'Ilijadu' i 'Odiseju'?", answers: ["Sofokle", "Homer", "Euripid", "Aristotel"], correct: 1 },
    { q: "Koliko ima dana u februaru tokom prestupne godine?", answers: ["28", "29", "30", "31"], correct: 1 },
    { q: "Koja je najveća životinja na kopnu?", answers: ["Nosorog", "Nilski konj", "Afrički slon", "Polarni medved"], correct: 2 },
    { q: "Ko je bio poslednji faraon Egipta?", answers: ["Ramzes II", "Tutankamon", "Kleopatra", "Nefertiti"], correct: 2 },
    { q: "Koliko sati traje jedan dan na Zemlji?", answers: ["12", "18", "24", "36"], correct: 2 },
    { q: "Koji je glavni grad Italije?", answers: ["Napulj", "Milano", "Firenca", "Rim"], correct: 3 },
    { q: "Kako se zove proces kojim biljke prave hranu?", answers: ["Disanje", "Fotosinteza", "Fermentacija", "Oksidacija"], correct: 1 },
    { q: "Koji je najmanji organ u ljudskom telu?", answers: ["Bubreg", "Slezina", "Epifiza", "Žučna kesa"], correct: 2 },
    { q: "Koliko ima kontinenata na Zemlji?", answers: ["5", "6", "7", "8"], correct: 2 },
    { q: "Koji je glavni grad Mađarske?", answers: ["Prag", "Beč", "Varšava", "Budimpešta"], correct: 3 },
    { q: "Koji sport se igra na Vimbldonu?", answers: ["Fudbal", "Kriket", "Tenis", "Golf"], correct: 2 }
];

async function run() {
    try {
        console.log("Povezivanje na bazu...");
        await mongoose.connect(MONGO_URI);
        
        console.log("Čišćenje stare baze (brisanje starih pitanja)...");
        await Question.deleteMany({});
        
        console.log("Ubacivanje novih 140+ pitanja...");
        const result = await Question.insertMany(questions);
        
        console.log("BRAVO! Ubačeno je tačno " + result.length + " pitanja u tvoju MongoDB bazu!");
        process.exit(0);
    } catch(e) {
        console.error("Desila se greška:", e);
        process.exit(1);
    }
}
run();
